### ISSUE TITLE
请问A53近期有支持计划吗？目前看只有A55 A510

### ISSUE THREAD

**Issue by xbwee1024** [MegEngine/mperf#7]
非常好的工具！高通骁龙400系列以及660及以下都是A53，市面上存量机型占比还比较多，期望能有针对A53的分析案例。目前的A55案例无法在A53 上跑通，有些pmu events没有。

**Comment by youzhedian** [comment]
a53的pmu缺一些event定义，所以最开始没选a53，但是如果想做可以做出来一个丐版的，近期可能没有计划做
